version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./storage:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
